config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  #いいね機能ルーティング
  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'

  #チャット機能のルーティング
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  root 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  #バリデーション
  validates :content, presence: true

end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :post, counter_cache: :likes_count
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  #refile
  attachment :image
  has_many :tags, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  #自分をフォローしているユーザー
  belongs_to :follower, class_name: "User"
  #自分がフォローしているユーザー
  belongs_to :following, class_name: "User"
  #バリデーション
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries
  has_many :chats

	def self.create_new_room_and_initial_entry(current_user, other_user)
	  room = create!
	  Entry.create!(user_id: current_user.id, room_id: room.id)
	  Entry.create!(user_id: other_user.id, room_id: room.id)
	  room
	end

end

app/models/tag.rb
class Tag < ApplicationRecord

	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_stories, through: :likes, source: :story
  has_many :entries
  has_many :chats
  #refile
  attachment :profile_image

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id])
    room_ids = current_user.entries.pluck(:room_id)
    entry = Entry.find_by(user_id: @user.id, room_id: room_ids)
    @room = unless entry.nil?
              entry.room
            else
              Room.create_new_room_and_initial_entry(current_user, @user)
            end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
			@posts = Post.all
			@comment = Comment.new
	end

	def show
			@post = Post.find(params[:id])
			@comment = Comment.new
			#新着順で表示
			@comments = @post.comments.order(created_at: :desc)
	end

	def create
			@post = Post.new(post_params)
			@post.user_id = current_user.id
			if  @post.save
			    tags = Vision.get_image_data(@post.image)
			    tags.each do |tag|
			      @post.tags.create(name: tag)
			    end
				  redirect_to posts_path, notice: "You have created book successfully."
			else
					@posts = Post.all
					redirect_to posts_path
			end
	end

	def edit
      @post = Post.find(params[:id])
	end

	def update
      @post = Post.find(params[:id])
      if  @post.update(post_params)
      	  tags = Vision.get_image_data(@post.image)
			    tags.each do |tag|
			   	  @post.tags.update(name: tag)
			    end
          redirect_to user_path(current_user), notice: "You have updated user successfully."
      else
          render "show"
		  end
	end

	def destroy
	    @post = Post.find(params[:id])
	    @post.destroy
	    redirect_to user_path(current_user)
	end

	private

	def post_params
      params.require(:post).permit(:image,:post_comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
  	@user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
      if @user.update(user_params)
         #パスワード変更を行った場合はログアウトするためサインインを実行してから実行する
         bypass_sign_in(@user)
         redirect_to user_path(@user), notice: "You have updated user successfully."
      else
        render "show"
      end
  end

  def following
    #@userがフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.following
    render 'index_follow'
  end

  def followers
    #@userをフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'index_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :profile_image, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サブメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', post:Post.new %>

　　<!-- メイン画面 -->
  	<div class='col-6'>
      <div class="card chat">
        <div class="card-header">
          <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg", size: "50x50", class: "rounded-circle" %>
          <%= @user.name %>
        </div>

        <div class="card-body">

            <% @chats.each do |chat| %>

              <% if chat.user.id == current_user.id %>
                <div class="row">
                  <div class="col-2 ml-auto p-1">
                    <p class="my-message"><%= chat.message %></p>
                  </div>
                </div>
              <% else %>
                <div class="row">
                  <div class="col-1">
                    <%= attachment_image_tag chat.user, :profile_image, :fill, 40, 40, fallback: "no-image.jpg", size: "40x40", class: "rounded-circle" %>
                  </div>
                  <div class="col-2 p-1">
                    <p class="other-message"><%= chat.message %></p>
                  </div>
                </div>
              <% end %>
            <% end %>

        </div>

        <div class="card-footer">
          <%= form_with model: @chat do |f| %>
            <%= f.text_field :message %>
            <%= f.hidden_field :room_id %>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= post.id %>">
  <% if current_user.likes.find_by(post_id: post.id) %>
    <%= link_to unlike_path(post.id), method: :delete, remote: true do %>
        <div class = "iine_button"><i class="fas fa-heart" style="color: red"></i><%= post.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to like_path(post.id), method: :post, remote: true do %>
        <div class = "iine_button"><i class="far fa-heart"></i><%= post.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/posts/_modal.html.erb
<!-- モーダル・ダイアログ(新規投稿) -->
<div class="modal fade" id="postModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_with model: Post.new, local: true do |f| %>
        <div class="modal-header">
          <h4 class="modal-title">新規投稿</h4>
          <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        </div>
        <div class="modal-body">
　　　　　　<div id="preview"></div>
          <div class="row">
            <div class="col-12 float-left">
　　　　　　    <%= f.attachment_field :image, onchange: "imgPreView(event)" %>
            </div>
          </div>
          <div class="row">
            <div class="col-5 text-right">
              <%= f.label "コメント" %>
            </div>
            <div class="col-7 text-left">
              <%= f.text_area :post_comment %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
          <%= f.submit "投稿", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<%= render 'likes/like', post: post %>

app/views/posts/_sidemenu.html.erb
<ul class='side-menu_fixed'>
  <li>
    <%= link_to posts_path do %>
      <%= image_tag "inchikigram_icon.png", class: "inchikigram_icon" %>
    <% end %>
  </li>
  <li>
    <%=link_to posts_path, class: "nav-link" do %>
      <i class="fas fa-home"></i> ホーム
    <% end %>
  </li>
  <li>
    <%= link_to user_path(current_user), class: "nav-link" do %>
      <i class="fas fa-user"></i> プロフィール
    <% end %>
  </li>
  <li>
    <%=link_to users_path, class: "nav-link" do %>
      <i class="fas fa-users"></i> User一覧
    <% end %>
  </li>
  <li>
    <%= link_to destroy_user_session_path, class: "nav-link", :method=>:delete, data: {confirm: "本当にログアウトしてもよろしいですか？"} do %>
      <i class="fas fa-sign-out-alt"></i> ログアウト
    <% end %>
  </li>
  <li>
    <button type="button" class="btn-lg btn-primary rounded-pill post-botton" data-toggle="modal" data-target="#postModal">
      <span>投稿する</span>
　　 </button>
  </li>
</ul>

app/views/posts/edit.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サブメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', posts:Post.new %>

    <div class='col-6 main'>
      <div class="row pt-3">
      	<div class='col-12 text-center'>
      	  <h2>投稿編集</h2>
      	</div>
      </div>
      <%= form_with model: @post, url:post_path(@post), method: :patch,  local: true do |f| %>
        <div class="row pt-3">
          <div id="preview"></div>
          <div class='col-12 text-center'>
            <%= f.attachment_field :image, onchange: "imgPreView(event)" %>
          </div>
        </div>
        <div class="row pt-5">
          <div class='col-5 text-right'>
	          <%= f.label '投稿コメント' %>
	        </div>
	        <div class='col-5'>
			      <%= f.text_area :post_comment %>
		      </div>
        </div>
        <div class="row pt-4">
          <div class='col-12 text-center'>
            <%= f.submit "保存", class: "btn btn-primary"  %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/index.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サブメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', posts:Post.new %>

    <div class='col-6 post-index-main'>
      <% @posts.each do |post| %>
			  <div class="card">
			    <div class="card-header">
			    	<%= attachment_image_tag post.user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg", size: "50x50", class: "rounded-circle" %>
			    	<%= post.user.name %>
			    	<%= link_to post_path(post), class: "show-icon" do %>
			    	  <i class="fa fa-ellipsis-h fa-lg"></i>
			    	<% end %>
			    </div>
			    <%= attachment_image_tag post, :image %>
			    <div class="card-body">
			    	<%= render partial: 'posts/posts', locals: { post: post }  %>
			    	<% post.tags.each do |tag| %>
			        <span class="label"><%= tag.name %></span>
			      <% end %>
			    </div>
			    <div class="card-text">
			    	<%= post.post_comment %>
			    </div>
			    <div class="card-footer" style="padding: 0px">
			    	<%= render partial: 'comments/form', locals: { comment: @comment, post: post } %>
			    </div>
			  </div>
	    <% end %>
    </div>

  </div>
</div>

app/views/posts/show.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サイドメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', posts:Post.new %>

    <div class='col-6 post-show-main'>
		  <div class="card">
		    <div class="card-header">
		    	<%= attachment_image_tag @post.user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg", size: "50x50", class: "rounded-circle" %>
		    	<%= @post.user.name %>
		    	<%= link_to user_path(@post.user.id), class: "user-show-icon" do %>
		    	  <i class="fa fa-ellipsis-h fa-lg"></i>
		    	<% end %>
		    </div>
		    <%= attachment_image_tag @post, :image %>
		    <div class="card-body">
		    	<%= render partial: 'posts/posts', locals: { post: @post }  %>
		    </div>
		    <div class="card-text">
		    	<%= @post.post_comment %>
		    </div>
		    <div class="card-footer" style="padding: 0px">
		    	<%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
			    <table>
			    	<tbody>
						  <% @comments.each do |comment| %>
				    		<tr>
				    			<td>
				    				<%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, fallback: "no-image.jpg", size: "40x40", class: "rounded-circle" %>
				    			</td>
				    			<td class="name">
				    				<%= comment.user.name %>
				    			</td>
				    		</tr>
				    		<tr>
				    			<td></td>
				    			<td></td>
				    			<td class="comment">
				    				<%= comment.content %>
				    			</td>
				    		</tr>
					  	<% end %>
		    		</tbody>
		    	</table>
		    </div>
		  </div>
    </div>

  </div>
</div>

app/views/users/_follow.html.erb
<!-- フォローボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- フォローボタン(MYPAGEのユーザーがcurrent_userでなければ表示-->
<% if user_signed_in? && user != current_user %>
    <% if current_user.following?(user) %>
      <%= render "unfollow", user:user%>
    <% else %>
      <%= render "follow", user:user %>
    <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<!-- フォロー解除ボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationship_path(user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サブメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', posts:Post.new %>

    <div class='col-6 main'>
      <div class="row pt-3">
      	<div class='col-12 text-center'>
      	  <h2>ユーザー編集</h2>
      	</div>
      </div>
      <%= form_with model: @user, url:user_path(@user), method: :patch,  local: true do |f| %>
        <div class="row pt-3">
          <div class='col-12 text-center'>
            <%= f.attachment_field :profile_image %>
          </div>
        </div>
        <div class="row pt-5">
          <div class='col-5 text-right'>
	        <%= f.label :name %>
	      </div>
	      <div class='col-5'>
			<%= f.text_field :name %>
		  </div>
        </div>
        <div class="row pt-4">
          <div class='col-5 text-right'>
            <%= f.label :email %>
          </div>
          <div class='col-5'>
		    <%= f.text_field :email %>
		  </div>
        </div>
        <div class="row pt-4">
          <div class='col-5 text-right'>
            <%= f.label :password %>
          </div>
          <div class='col-5'>
		    <%= f.password_field :password %>
		  </div>
        </div>
        <div class="row pt-4">
          <div class='col-5 text-right'>
            <%= f.label :password_confirmation %>
          </div>
          <div class='col-5'>
		    <%= f.password_field :password_confirmation %>
		  </div>
        </div>
        <div class="row pt-4">
          <div class='col-12 text-center'>
            <%= f.submit "保存", class: "btn btn-primary"  %>
          </div>
        </div>
	  <% end %>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サブメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', post:Post.new %>

　　<!-- メイン画面 -->
  	<div class='col-5 users-main'>
  	  <div class='row p-2'>
        <div class='col-12 text-center'>
          <h2>ユーザー(一覧)</h2>
        </div>
      </div>
  	  <% @users.each do |user| %>
        <div class="row">
          <div class="col-2">
            <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg", size: "50x50", class: "rounded-circle" %>
          </div>
          <div class="col-2">
  	  	    <%= user.name %>
  	  	  </div>
          <div class="col-4">
            <div id="follow_form_<%= user.id %>">
            　<%= render "follow_form", user:user %>
            </div>
          </div>
  	  	  <div class="col-2">
          　<% if current_user != user.id %>
　　　　　　　  <%= link_to chat_path(user.id) do %>
                <i class="far fa-comment fa-lg"></i>
              <% end %>
　　　　　　　<% end %>
          </div>
  	    </div>
  	  <% end %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<!-- container-fluid → 可変幅のコンテナ(ウィンドウサイズを変えても常に画面いっぱいに広がる -->
<div class='container-fluid'>
  <div class='row'>

　　<!-- サブメニュー -->
  	<div class='col-3'>
      <%= render 'posts/sidemenu' %>
  	</div>
　  <!-- 投稿ボタン -->
    <%= render 'posts/modal', posts:Post.new %>

    <div class='col-6 user-show-main'>
      <div class="card">
        <div class="card-header">
    	    <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no-image.jpg", size: "50x50", class: "rounded-circle" %>
    	    <%= @user.name %>
          <% if @user == current_user %>
    	      <%= link_to edit_user_path(@user), class: "user-edit-icon" do %>
              <i class="fa fa-gear fa-lg "></i>
            <% end %>
          <% end %>
        </div>
    	  <% @posts.each do |post| %>
    	  	<%= attachment_image_tag post, :image %>
    	  	<div class="card-body">
            <% if @user == current_user %>
      	  	  <%= link_to post_path(post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "post-delete-icon destroy_post_#{post.id}" do %>
                <i class="fa fa-trash-o fa-lg  "></i>
              <% end %>
              <%= link_to edit_post_path(post.id), class: "post-edit-icon" do %>
                <i class="fa fa-wrench fa-lg  "></i>
              <% end %>
            <% end %>
    	  	  <div class="card-text">
    	  	  	<%= post.post_comment %>
    	  	  </div>
    	  	</div>
    	  <% end %>
      </div>

  </div>
</div>